### ISSUE TITLE
no bones for gltf model

### ISSUE THREAD

**Issue by oxplay2** [stephengold/Minie#1] opened 2019-01-14 01:45 UTC
I think there is problem with model - gltf exported model to j3o.

i always get shader error for even simple model, attach below

Uncaught exception thrown in Thread[jME3 Main,5,main]
RendererException: compile error in: ShaderSource[name=Common/MatDefs/Shadow/PreShadow.vert, defines, type=Vertex, language=GLSL150]
Vertex shader failed to compile with the following errors:
ERROR: 0:157: error(#102) #error:  NUM_BONES must be between 1 and 255.
ERROR: 0:164: error(#186) Array size must be a positive integer
ERROR: error(#273) 2 compilation errors.  No code generated

How much am i sure its Minie issue?
Because i just used Minie examples, replaced PuppetControl(removed interface) with one link "Armature_Arm", replaced Anim name in balanceTest to "cubeAnim" and model dir.

so i think its about model exported via gltf dont work.

this file was exported using https://github.com/KhronosGroup/glTF-Blender-Exporter/

(its older version of https://github.com/KhronosGroup/glTF-Blender-IO that correctly export animation to JME)

it have example static animation named "cubeAction"

[test3.zip](https://github.com/stephengold/Minie/files/2753825/test3.zip)

**Comment by stephengold** [comment] 2019-01-14 16:59
I'm unable to load the glTF file because it requires a file `test3.bin` that you haven't provided yet.

**Comment by stephengold** [comment] 2019-01-14 17:05
The `test3.j3o` loads in JME 3.2.2 for me.

I added a `DynamicAnimControl`, but I don't get the `RendererException` you reported. Could share your test code?

**Comment by oxplay2** [comment] 2019-01-14 18:50
all changes visible on screenshots. Its Minie -> MinieExamples subproject changes.
attatching new zip file with more files.

![changes](https://user-images.githubusercontent.com/45903579/51133243-bf65da00-1834-11e9-85d2-2036b60c488d.JPG)

![changes2](https://user-images.githubusercontent.com/45903579/51133292-e6bca700-1834-11e9-98ff-10bc75b09e8c.JPG)

![changes3](https://user-images.githubusercontent.com/45903579/51133332-048a0c00-1835-11e9-995e-cb6b9c1cd249.JPG)
(all links replaced with this one - Cube_Arm that is child of Cube_Main)

test3.zip](https://github.com/stephengold/Minie/files/2756617/test3.zip)

Also you said it work for you, can i know did you it same way as me? what export from blender did you use and what blender version. i got 2.79b blender and exporter provided link before.

please also note i have AMD Radeon card, since it is shader error and i got Radeon and you NVidia, maybe its something in shader that Radeon dont take well.

**Comment by stephengold** [comment] 2019-01-14 21:41
Recreating your work from screenshots was difficult. Next time, send text.

I reproduced the `RendererException` by pressing F8 in the modified `BalanceDemo` application. 

Although the model has 2 bones, the model's "Cube" `Node` has a material-parameter override for `NumberOfBones=0`. I'm unsure why. And that's what triggers the `RendererException`.

I know the `NumberOfBones` material-parameter override is configured by `SkeletonControl`. I'm investigating why it ends up set to 0 instead of 2.

**Comment by stephengold** [comment] 2019-01-14 22:16
`SkeletonControl` doesn't configure the override because software skinning is used. For software skinning, the `NumberOfBones` override should be disabled. But when the J3O was loaded, the override was enabled.

If I disabled overrides using
```
        cgModel = (Node) assetManager.loadModel("Models/Puppet/test3.j3o");
        Spatial cube = cgModel.getChild(0);
        for (MatParamOverride o : cube.getLocalMatParamOverrides()) {
           o.setEnabled(false);
        }
```
then the `RendererException` is no longer thrown.

I continue to investigate this.

**Comment by oxplay2** [comment] 2019-01-15 04:36
yes i export to j3o via SDK.

so you say the fix in 3.2.2 was for exporter too(IDE), not just loader?

i remember you said you use 3.2.1 SDK too, so thought its ok. but i did not thought that you can convert it other way, or just dont convert and load as gltf. 

i cant update it via "check updates" so hope there is downloadable version of 3.2.2.

anyway you sure it will help?

**Comment by stephengold** [comment] 2019-01-15 05:08
The 3.2.1 SDK used the 3.2.1 libraries. So of course bugs in the libraries can affect the IDE as well. Before today, I hadn't considered that this particular bug would affect the SDK.

While I do use the 3.2.1 SDK, I don't use the SDK to convert models to J3O. I write my own converters, using code similar to this:
 https://hub.jmonkeyengine.org/t/ragdoll-issue-gltf-model-bonus-gradle-discussion/41278/39

There is a downloadable 3.2.2 SDK:
  https://github.com/jMonkeyEngine/sdk/releases/tag/v3.2.2-stable-sdk1

However, I find it unusable due to this issue:
  https://github.com/jMonkeyEngine/sdk/issues/187

I hope it works for you.

**Comment by oxplay2** [comment] 2019-01-15 05:11
hmm. i will try find some way to not export it via 3.2.1, because i got windows here so unstable IDE might be a problem.

**Comment by stephengold** [comment] 2019-01-15 17:14
May I close this issue?

**Comment by oxplay2** [comment] 2019-01-15 19:21
yes, please.

**Closed** 2019-01-15 19:59 UTC
